#
# CircleCI configuration for @thisissoon/angular-image-loader
#

version: 2

jobs:
  setup:
    working_directory: ~/@thisissoon/angular-image-loader
    docker:
      - image: circleci/node:8-browsers
    steps:
      - checkout
      - restore_cache:
          key: ~/@thisissoon/angular-image-loader-{{ .Branch }}-{{ checksum "package.json" }}
      - run: yarn --silent
      - save_cache:
          key: ~/@thisissoon/angular-image-loader-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - 'node_modules'

  test:
    working_directory: ~/@thisissoon/angular-image-loader
    docker:
      - image: circleci/node:8-browsers
    steps:
      - checkout
      - restore_cache:
          key: ~/@thisissoon/angular-image-loader-{{ .Branch }}-{{ checksum "package.json" }}
      - run: yarn lint
      - run: yarn test --configuration ci
      - run: yarn e2e
      - run: yarn coverage

workflows:
  version: 2
  setup_and_test:
    jobs:
      - setup
      - test:
          requires:
            - setup
